package internal

import (
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/BurntSushi/toml"
)

// LockVersion is the format this build reads and writes. A lock from another
// version is an error rather than a guess: the host CLI that owns the file
// decides how to migrate it.
const LockVersion = 2

const lockHeader = "# Generated by lpm. Commit this file.\n"

// LockedPackage is one resolved package, pinned to the version and the
// digests a later run has to reproduce.
type LockedPackage struct {
	Name     string `toml:"name"`
	Version  string `toml:"version"`
	Platform string `toml:"platform"`
	Registry string `toml:"registry"`
	// "name version" for each dependency, sorted. The resolved version, not
	// the requirement: the requirement is the registry's to answer again.
	Dependencies []string `toml:"dependencies"`
	// target -> "sha256:..." for every artifact lpm has verified. A run on
	// another machine adds its own target and leaves these alone.
	Artifacts map[string]string `toml:"artifacts"`
}

type Lock struct {
	Version  int             `toml:"version"`
	Packages []LockedPackage `toml:"package"`
}

// Find returns the pin for name.
func (l *Lock) Find(name string) (LockedPackage, bool) {
	if l == nil {
		return LockedPackage{}, false
	}
	for _, p := range l.Packages {
		if p.Name == name {
			return p, true
		}
	}
	return LockedPackage{}, false
}

// ReadLock loads a lock file. A missing file is an empty lock, so the first
// install writes one rather than failing.
func ReadLock(path string) (*Lock, error) {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &Lock{Version: LockVersion}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	var lock Lock
	if err := toml.Unmarshal(raw, &lock); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if lock.Version != LockVersion {
		return nil, fmt.Errorf("%s is lock version %d, and this lpm writes version %d",
			path, lock.Version, LockVersion)
	}

	for i := range lock.Packages {
		if lock.Packages[i].Artifacts == nil {
			lock.Packages[i].Artifacts = map[string]string{}
		}
	}
	return &lock, nil
}

// Encode renders the lock. Packages go out sorted by name and every map is
// written in key order, so the same resolution produces the same bytes and a
// diff shows what changed rather than how the map was walked.
func (l *Lock) Encode() []byte {
	packages := slices.Clone(l.Packages)
	slices.SortFunc(packages, func(a, b LockedPackage) int {
		return strings.Compare(a.Name, b.Name)
	})

	var b strings.Builder
	b.WriteString(lockHeader)
	fmt.Fprintf(&b, "version = %d\n", LockVersion)

	for _, p := range packages {
		b.WriteString("\n[[package]]\n")
		fmt.Fprintf(&b, "name = %q\n", p.Name)
		fmt.Fprintf(&b, "version = %q\n", p.Version)
		fmt.Fprintf(&b, "platform = %q\n", p.Platform)
		fmt.Fprintf(&b, "registry = %q\n", p.Registry)

		deps := slices.Sorted(slices.Values(p.Dependencies))
		quoted := make([]string, len(deps))
		for i, d := range deps {
			quoted[i] = fmt.Sprintf("%q", d)
		}
		fmt.Fprintf(&b, "dependencies = [%s]\n", strings.Join(quoted, ", "))

		if len(p.Artifacts) > 0 {
			b.WriteString("\n[package.artifacts]\n")
			for _, target := range slices.Sorted(maps.Keys(p.Artifacts)) {
				fmt.Fprintf(&b, "%s = %q\n", target, p.Artifacts[target])
			}
		}
	}

	return []byte(b.String())
}

// Equal reports whether two locks would be written identically. It is how
// `--locked` decides the lock is stale without writing anything.
func (l *Lock) Equal(other *Lock) bool {
	return string(l.Encode()) == string(other.Encode())
}

// WriteLock replaces the file through a temporary one in the same directory,
// so an interrupted write never leaves a half-written lock behind.
func WriteLock(path string, lock *Lock) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}

	tmp, err := os.CreateTemp(dir, ".lpm-lock-*")
	if err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	defer os.Remove(tmp.Name())

	if _, err := tmp.Write(lock.Encode()); err != nil {
		tmp.Close()
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
