package internal

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func sampleLock() *Lock {
	return &Lock{
		Version: LockVersion,
		Packages: []LockedPackage{
			{
				Name:         "shape-tools",
				Version:      "1.2.3",
				Platform:     "lumen",
				Registry:     "https://reg.lumenfx.dev",
				Dependencies: []string{"geom 0.3.1"},
				Artifacts: map[string]string{
					"linux-x86_64": "sha256:0123",
					AnyTarget:      "sha256:4567",
				},
			},
			{
				Name:         "geom",
				Version:      "0.3.1",
				Platform:     "lumen",
				Registry:     "https://reg.lumenfx.dev",
				Dependencies: []string{},
				Artifacts:    map[string]string{AnyTarget: "sha256:89ab"},
			},
		},
	}
}

func TestLockRoundTrips(t *testing.T) {
	path := filepath.Join(t.TempDir(), "lumen.lock")
	if err := WriteLock(path, sampleLock()); err != nil {
		t.Fatal(err)
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := string(raw)
	if !strings.HasPrefix(text, "# Generated by lpm. Commit this file.\n") {
		t.Errorf("lock = %q, want the header first", text)
	}
	// Sorted by name, so geom comes before shape-tools however they resolved.
	if strings.Index(text, `name = "geom"`) > strings.Index(text, `name = "shape-tools"`) {
		t.Errorf("lock = %q, want packages sorted by name", text)
	}
	if !strings.Contains(text, "[package.artifacts]") ||
		!strings.Contains(text, `linux-x86_64 = "sha256:0123"`) {
		t.Errorf("lock = %q, want the artifact table", text)
	}

	read, err := ReadLock(path)
	if err != nil {
		t.Fatal(err)
	}
	if !read.Equal(sampleLock()) {
		t.Errorf("read back %q, want the lock that was written", read.Encode())
	}
}

// The same resolution has to produce the same bytes, whichever way the maps
// happened to be walked.
func TestLockEncodesTheSameBytesTwice(t *testing.T) {
	first := sampleLock().Encode()
	for range 20 {
		if got := sampleLock().Encode(); string(got) != string(first) {
			t.Fatalf("encode = %q, want %q", got, first)
		}
	}
}

func TestReadLockTreatsAMissingFileAsEmpty(t *testing.T) {
	lock, err := ReadLock(filepath.Join(t.TempDir(), "nothing-here.lock"))
	if err != nil {
		t.Fatal(err)
	}
	if lock.Version != LockVersion || len(lock.Packages) != 0 {
		t.Errorf("lock = %+v, want an empty version %d lock", lock, LockVersion)
	}
}

func TestReadLockRejectsAnotherVersion(t *testing.T) {
	path := filepath.Join(t.TempDir(), "lumen.lock")
	if err := os.WriteFile(path, []byte("version = 7\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, err := ReadLock(path)
	if err == nil || !strings.Contains(err.Error(), "version 7") {
		t.Errorf("ReadLock = %v, want an error naming version 7", err)
	}
}

func TestReadLockReportsBrokenToml(t *testing.T) {
	path := filepath.Join(t.TempDir(), "lumen.lock")
	if err := os.WriteFile(path, []byte("version = \n[[package\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := ReadLock(path); err == nil {
		t.Error("ReadLock accepted a file that is not TOML")
	}
}

func TestLockFindAndEqual(t *testing.T) {
	lock := sampleLock()

	pin, ok := lock.Find("geom")
	if !ok || pin.Version != "0.3.1" {
		t.Errorf("Find(geom) = %+v, %v, want 0.3.1", pin, ok)
	}
	if _, ok := lock.Find("absent"); ok {
		t.Error("Find(absent) found something")
	}

	var missing *Lock
	if _, ok := missing.Find("geom"); ok {
		t.Error("Find on a nil lock found something")
	}

	other := sampleLock()
	other.Packages[0].Version = "1.2.4"
	if lock.Equal(other) {
		t.Error("two locks with different versions compared equal")
	}
}

func TestWriteLockReplacesAnExistingFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nested", "lumen.lock")
	if err := WriteLock(path, &Lock{Version: LockVersion}); err != nil {
		t.Fatal(err)
	}
	if err := WriteLock(path, sampleLock()); err != nil {
		t.Fatal(err)
	}

	read, err := ReadLock(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(read.Packages) != 2 {
		t.Errorf("lock holds %d packages, want 2", len(read.Packages))
	}

	// The temporary file it wrote through is gone.
	entries, err := os.ReadDir(filepath.Dir(path))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Errorf("directory holds %d entries, want the lock alone", len(entries))
	}
}

func TestWriteLockReportsADirectoryItCannotUse(t *testing.T) {
	// A file where the lock's directory should be, so creating it fails.
	root := t.TempDir()
	blocker := filepath.Join(root, "blocked")
	if err := os.WriteFile(blocker, []byte("not a directory"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := WriteLock(filepath.Join(blocker, "lumen.lock"), sampleLock()); err == nil {
		t.Error("WriteLock succeeded where it cannot create a directory")
	}

	if runtime.GOOS == "windows" {
		t.Skip("chmod does not take a write bit off a directory on Windows")
	}
	if os.Getuid() == 0 {
		t.Skip("root writes into a directory with no write bit")
	}
	readonly := filepath.Join(root, "readonly")
	if err := os.Mkdir(readonly, 0o500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.Chmod(readonly, 0o700) })

	if err := WriteLock(filepath.Join(readonly, "lumen.lock"), sampleLock()); err == nil {
		t.Error("WriteLock succeeded in a directory it cannot write to")
	}
}
