apiVersion: v1
kind: Service
metadata:
  name: lpm-server
  namespace: lpm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lpm-server
  ports:
    - name: http
      port: 80
      targetPort: http
